version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/src:cached # Source Directory
      - ./site:/var/www/web:cached # Build directory
      - ./scripts:/var/www/scripts:cached # Scripts directory
      - ./db-backups:/var/www/db-backups:cached
      - ./flight-deck.yml:/config/web/flightdeck-web.yml
    environment:
      - JEKYLL_ENV=development
