# TEN7 Jekyll Workflow

name: Build

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      git-username:
        required: true
        type: string
      git-email:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout branch
        run: git checkout ${{ github.ref_name }}
        
      - name: Build Preview or Develop 
        if: inputs.branch == ('develop' || 'preview')
        run: cd $GITHUB_WORKSPACE/web
        run: bundle config set --local path 'vendor/bundle'
        run: bundle install
        run: bundle exec jekyll build --config _config.yml,_config_dev.yml --destination $GITHUB_WORKSPACE/web/_build
        
      # Build Main branch
      - name: Build main
        if: github.ref_name == 'main'
        run: cd $GITHUB_WORKSPACE/web
        run: bundle config set --local path 'vendor/bundle'
        run: bundle install
        run: bundle exec jekyll build
        
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          touch .nojekyll
          git config --global user.email ${{ inputs.git-email }}
          git config --global user.name ${{ inputs.git-username }}
          git add .
          git commit -a -m "Automated build from commit: $GITHUB_SHA"
