# TEN7 Jekyll Deployment Workflow
name: Deployment

env:
  GH_USER: madeline-holland
  GH_USER_EMAIL: madeline.holland@ten7.com
  BUILD_DIR: ${GITHUB_WORKSPACE}/build
  REPO_DIR: ${GITHUB_WORKSPACE}/src
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - develop
      - preview
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout build repo
        if: github.ref_name == 'main'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: web/_build

      - name: Checkout dev / preview build repo
        if: github.ref_name == ('develop' || 'preview')
        uses: actions/checkout@v3
        with:
          ref: ${{ format('gh-pages-{0}', github.ref_name) }}
          path: web/_build

      - name: Setup Ruby Pkgs
        uses: ruby/setup-ruby-pkgs@v1.32.0
        with:
          bundler-cache: true
          working-directory: web
          ruby-version: '3.0'
        
      - name: Build Preview or Develop 
        if: github.ref_name == ('develop' || 'preview')
        run: |
          cd $GITHUB_WORKSPACE/web
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec jekyll clean --destination _build
          bundle exec jekyll build --config _config.yml,_config_dev.yml --destination _build
        
      # Build Main branch
      - name: Build main
        if: github.ref_name == 'main'
        run: | 
          cd $GITHUB_WORKSPACE/web
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec jekyll clean
          bundle exec jekyll build
        
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          touch .nojekyll
          git config --global user.email ${{ env.GH_USER_EMAIL }}
          git config --global user.name ${{ env.GH_USER }}
          git add .
          git commit -a -m "Automated build from commit: $GITHUB_SHA"
        continue-on-error: true
         
      - name: Deploy main
        if: ${{ github.ref_name == 'main' }} 
        run: | 
          cd $GITHUB_WORKSPACE/web/_build
          git push -f
          
      - name: Push develop
        if: ${{ github.ref_name == 'develop' }}
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          git push --force origin HEAD:gh-pages-develop
          
      - name: Push preview
        if: ${{ github.ref_name == 'preview' }}
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          git push --force origin HEAD:gh-pages-preview
