# TEN7 Jekyll Workflow

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - develop
      - preview

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clone:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
     
      # Check out the gh-pages branch into _build
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: web/_build

  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Set up Ruby environment
      - name: Setup Ruby Pkgs
        uses: ruby/setup-ruby-pkgs@v1.32.0
        with:
          bundler-cache: true
          working-directory: web
          ruby-version: '3.0'
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: clone
    steps: 
      # Set Jekyll to build into _build
      - name: Replace build directory
        run: |
          cd $GITHUB_WORKSPACE/web
          sed -e "s/destination\: \/var\/www\/web/destination\: \_build/" _config.yml > tmp_file
          mv tmp_file _config.yml
      
      # Build Jekyll
      - name: Build Jekyll site
        run: |
          cd $GITHUB_WORKSPACE/web
          bundle config set --local path 'vendor/bundle'
          bundle install
          bundle exec jekyll build
          
  commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Commit changes
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          touch .nojekyll
          git config --global user.email "madeline.holland@ten7.com"
          git config --global user.name "Madeline Holland"
          echo $(ls)
          git add .
          git commit -a -m "Automated build from commit: $GITHUB_SHA"
         
  deploy_main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Deploy main
        if: ${{ github.ref_name == 'main' }}
        run: | 
          cd $GITHUB_WORKSPACE/web/_build
          git push -f
          
  deploy_develop:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Push develop
        if: ${{ github.ref_name == 'develop' }}
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          git push --force origin HEAD:gh-pages-develop
          
  deploy_preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: commit
    steps:
      - name: Push preview
        if: ${{ github.ref_name == 'preview' }}
        run: |
          cd $GITHUB_WORKSPACE/web/_build
          git push --force origin HEAD:gh-pages-preview
