# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# Build theme settings
# theme: minima

# List of plugins to use
plugins:
  - jekyll-seo-tag
  
# Set URL and subpath for Local development
url: "http://history.innocenceproject.test" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of the site
destination: /var/www/web

# Set build paths
source: .
#collections_dir: collections
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass # This is relative to "source" variable, not working direcotry

# Make sure to explicitly include the pages and assets directories
include: [pages,assets]

# List of files and directories to exclude from processing when building the site.
exclude:
  - _build # Only used on GitHub CI
  - vendor # Ruby Jekyll dependencies
  - Gemfile # Jekyll site dependency definitions
  - Gemfile.lock # Version lock.
  - "*.gitkeep" # Used to keep folders from being culled by Git
  - "*.gitignore" # Just in case
  - CNAME # Used for Domains by GitHub
  - gemfiles # gem
  - vendor # Node dependencies
  - node_modules
  - package-lock.json
  - package.json

# Disk cache has issues with the Docker setup, so we disable it.
disable_disk_cache: true 

# Site metadata
#  Note:
#    These files do not update inside the Docker container when changed
#    Run 'docker compose restart' to update its state inside the container 
#    Then restart building with 'bundle exec jekyll build --watch'
#
title: Innocence Project History
email: your-email@example.com
description: >- # this means to ignore newlines until "twitter_username:"
  Timeline history of Innocence Project: Realizing the power of DNA testing in ending wrongful convictions, Barry Scheck and Peter Neufeld founded the Innocence Project as a law clinic at the Benjamin N. Cardozo School of Law in 1992.
twitter_username: innocence
github_username: ten7
preview-image: https://history.innocenceproject.org/assets/images/hero/top-1.jpg

# feed:
#   disable_in_development: true

collections:
  timeline:
    output: false


