# These two are important for GitHub, do not change until ready! 
url: "https://ten7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/history.innocenceproject.org" # the subpath of your site, e.g. /blog
# Build output location for GitHub
destination: ../../build
